<?php

declare(strict_types=1);

namespace App\Livewire\Episode\Forms;

use App\Enums\Status as EmployeeStatus;
use App\Models\Employee\Employee;
use App\Rules\InDictionary;
use App\Rules\PastDateTime;
use Closure;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Locked;
use Livewire\Form;

class EpisodeForm extends Form
{
    /**
     * Episode UUID generated by the MIS and sent as the `id` of the request.
     *
     * @var string
     */
    #[Locked]
    public string $id = '';

    /**
     * Local ID of the episode being edited, kept out of the UUID uniqueness check.
     *
     * @var int|null
     */
    #[Locked]
    public ?int $episodeId = null;

    public string $name = '';

    public string $typeCode = '';

    public string $careManagerId = '';

    public string $startDate = '';

    public string $startTime = '';

    /**
     * Rules for an episode that is not known to eHealth yet, so every field is still editable.
     *
     * @return array
     */
    public function rulesForCreate(): array
    {
        return [
            'id' => ['required', 'uuid', Rule::unique('episodes', 'uuid')->ignore($this->episodeId)],
            'typeCode' => [
                'required',
                'string',
                new InDictionary('eHealth/episode_types'),
                $this->validateTypeForLegalEntityType(...),
                $this->validateTypeForEmployeeType(...)
            ],
            'name' => ['required', 'string', 'max:255'],
            'careManagerId' => ['required', 'uuid', $this->validateCareManager(...)],
            'startDate' => ['required', 'date', 'before_or_equal:today'],
            'startTime' => ['required', 'date_format:H:i', new PastDateTime($this->startDate)]
        ];
    }

    /**
     * Rules for the fields eHealth allows to change on an existing episode.
     *
     * @return array
     */
    public function rulesForUpdate(): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'careManagerId' => [
                'required',
                'uuid',
                $this->validateCareManager(...),
                $this->validateTypeForEmployeeType(...)
            ]
        ];
    }

    /**
     * Ensure the episode type is allowed for the type of the current legal entity.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @param  Closure  $fail
     * @return void
     */
    protected function validateTypeForLegalEntityType(string $attribute, mixed $value, Closure $fail): void
    {
        $allowedTypes = config('ehealth.legal_entity_episode_types.' . legalEntity()->type->name, []);

        if (!in_array($value, $allowedTypes, true)) {
            $fail(
                __('episodes.validation.type_forbidden_for_legal_entity', ['type' => $this->episodeTypeLabel($value)])
            );
        }
    }

    /**
     * Ensure the episode type is allowed for the employee type of the selected care manager.
     * Reads the type off the form so the rule can be attached either to the type or to the care manager.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @param  Closure  $fail
     * @return void
     */
    protected function validateTypeForEmployeeType(string $attribute, mixed $value, Closure $fail): void
    {
        $allowedTypes = config(
            'ehealth.employee_episode_types.' . $this->careManagerEmployee()?->employeeType,
            []
        );

        if (!in_array($this->typeCode, $allowedTypes, true)) {
            $fail(__('episodes.validation.type_forbidden_for_employee', [
                'type' => $this->episodeTypeLabel($this->typeCode)
            ]));
        }
    }

    /**
     * Ensure the selected care manager is an active employee that is allowed to manage an episode.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @param  Closure  $fail
     * @return void
     */
    protected function validateCareManager(string $attribute, mixed $value, Closure $fail): void
    {
        $careManager = $this->careManagerEmployee();
        $allowedTypes = config('ehealth.allowed_episode_care_manager_employee_types', []);

        if ($careManager === null) {
            $fail(__('episodes.validation.care_manager_not_in_legal_entity'));

            return;
        }

        if (!in_array($careManager->employeeType, $allowedTypes, true)) {
            $fail(__('episodes.validation.care_manager_type_not_allowed'));

            return;
        }

        if ($careManager->status !== EmployeeStatus::APPROVED || !$careManager->isActive) {
            $fail(__('episodes.validation.care_manager_not_active'));
        }
    }

    /**
     * Get the dictionary name of the episode type.
     *
     * @param  string  $code
     * @return string
     */
    protected function episodeTypeLabel(string $code): string
    {
        return dictionary()->basics()->byName('eHealth/episode_types')->asCodeDescription()->get($code);
    }

    /**
     * Get the employee of the current legal entity selected as a care manager.
     *
     * @return Employee|null
     */
    protected function careManagerEmployee(): ?Employee
    {
        if ($this->careManagerId === '') {
            return null;
        }

        return Employee::whereUuid($this->careManagerId)
            ->whereLegalEntityId(legalEntity()->id)
            ->first(['id', 'employee_type', 'status', 'is_active']);
    }

    /**
     * Redefine field names for error messages.
     *
     * @return array
     */
    public function validationAttributes(): array
    {
        return [
            'name' => __('episodes.name'),
            'typeCode' => __('episodes.type'),
            'careManagerId' => __('episodes.attending_doctor'),
            'startDate' => __('forms.start_date'),
            'startTime' => __('forms.start_time')
        ];
    }

    /**
     * Custom validation messages.
     *
     * @return array
     */
    protected function messages(): array
    {
        return ['id.unique' => __('episodes.validation.id_exists')];
    }
}
