<?php

return [
	'LABORANT' => [
		'employee_request:read', 'employee_request:approve', 'employee_request:reject', 'employee:read', 'employee_role:read', 'diagnostic_report:write', 'diagnostic_report:read', 'diagnostic_report:cancel', 'service_request:read', 'service_request:makeinprogress', 'service_request:use', 'service_request:complete', 'division:read', 'legal_entity:read', 'job:read', 'observation:read', 'observation:write', 'specimen:write', 'specimen:read', 'specimen:process', 'specimen:cancel', 'specimen:reject', 'specimen:invalidate', 'service_request:read_impersonal', 'device_definition:read', 'equipment:read', 'equipment:write', 
	],
	'HR' => [
		'division:details', 'division:write', 'division:activate', 'division:deactivate', 'division:read', 'employee:read', 'employee:write', 'employee:details', 'employee:deactivate', 'employee_request:approve', 'employee_request:reject', 'employee_request:write', 'employee_request:read', 'legal_entity:read', 'healthcare_service:read', 'healthcare_service:write', 'employee_role:read', 'employee_role:write', 'license:read', 'license:details', 'party_verification:details', 'party_verification:write', 'party_verification:read', 
	],
	'RECEPTIONIST' => [
		'declaration:read', 'declaration_request:approve', 'declaration_request:reject', 'declaration_request:read', 'declaration_request:write', 'capitation_report:read', 'division:details', 'division:read', 'employee:read', 'employee_request:approve', 'employee_request:reject', 'legal_entity:read', 'otp:read', 'otp:write', 'person:read', 'service_request:read', 'service_request:use', 'approval:create', 'healthcare_service:read', 'employee_role:read', 'person_request:write', 'person_request:read', 'preperson:read', 'preperson:write', 'authentication_method_request:write', 'merge_request:write', 'merge_request:read', 'job:read', 'observation:write', 'allergy_intolerance:write', 'medication_statement:write', 'risk_assessment:write', 'medication_administration:write', 'license:read', 'license:details', 'medical_event_context:read', 'person_verification:details', 'confidant_person_relationship:read', 
	],
	'PHARMACY_OWNER' => [
		'employee_role:write', 'employee_role:read', 'healthcare_service:write', 'healthcare_service:read', 'division:activate', 'division:deactivate', 'division:details', 'division:read', 'division:write', 'employee:deactivate', 'employee:details', 'employee:read', 'employee:write', 'employee_request:approve', 'employee_request:read', 'employee_request:reject', 'employee_request:write', 'legal_entity:read', 'otp:read', 'otp:write', 'secret:refresh', 'client:read', 'connection:read', 'connection:write', 'connection:refresh_secret', 'connection:delete', 'contract_request:create', 'contract_request:read', 'contract_request:terminate', 'contract_request:approve', 'contract_request:sign', 'contract:read', 'contract:write', 'medical_program_provision:write', 'medical_program_provision:read', 'license:details', 'license:read', 'license:write', 'medication_dispense:read_pharm', 'medication_request:details_pharm', 'party_verification:details', 'party_verification:write', 'device_dispense:read', 'medication_request:read_pharm', 
	],
	'DOCTOR' => [
		'declaration:read', 'declaration_request:approve', 'declaration_request:read', 'declaration_request:sign', 'declaration_request:write', 'division:read', 'employee:read', 'employee_request:approve', 'employee_request:reject', 'employee_request:read', 'legal_entity:read', 'otp:read', 'otp:write', 'person:read', 'patient_summary:read', 'encounter:write', 'encounter:read', 'encounter:cancel', 'episode:write', 'episode:read', 'job:read', 'condition:read', 'condition:write', 'observation:read', 'observation:write', 'immunization:read', 'immunization:write', 'allergy_intolerance:read', 'allergy_intolerance:write', 'medication_statement:read', 'medication_statement:write', 'device:read', 'device:write', 'risk_assessment:read', 'risk_assessment:write', 'medication_dispense:read', 'drugs:read', 'medication_request:details', 'medication_request:read', 'medication_request:reject', 'medication_request:resend', 'medication_request_request:read', 'medication_request_request:reject', 'medication_request_request:sign', 'medication_request_request:write', 'diagnostic_report:read', 'diagnostic_report:write', 'diagnostic_report:cancel', 'procedure:read', 'procedure:write', 'procedure:cancel', 'service_request:makeinprogress', 'service_request:complete', 'service_request:recall', 'service_request:cancel', 'service_request:write', 'service_request:read', 'service_request:use', 'approval:create', 'program_service:read', 'medication_administration:read', 'medication_administration:write', 'healthcare_service:read', 'employee_role:read', 'person_request:write', 'person_request:read', 'person_request:sign', 'authentication_method_request:write', 'care_plan:read', 'approval:read', 'approval:cancel', 'care_plan:write', 'composition:create', 'composition:sign', 'composition:cancel', 'composition:read', 'composition:write', 'composition:mark_in_error', 'composition:resend_sms', 'composition_configuration:read', 'composition:search', 'license:read', 'clinical_impression:read', 'rule_engine_rule:read', 'medical_event_context:read', 'clinical_impression:write', 'person_verification:details', 'person_verification:write', 'person_emergency_contact:read', 'device_definition:read', 'device_request:write', 'device_request:read', 'device_request:resend', 'device_request:revoke', 'specimen:write', 'specimen:read', 'specimen:process', 'specimen:cancel', 'specimen:reject', 'specimen:invalidate', 'confidant_person_relationship_request:write', 'confidant_person_relationship_request:read', 'confidant_person_relationship:read', 'device_request:mark_in_error', 'device_request:complete', 'device_dispense:read', 'device_association:read', 'detected_issue:read', 'devices_configurations:read', 'device_parameters_configurations:read', 'dictionaries_configurations:read', 'observation_configurations:read', 'care_team:write', 'care_team:read', 'person_verification:read', 'personal_data:read', 'equipment:read', 'equipment:write', 
	],
	'PHARMACIST' => [
		'division:read', 'employee:read', 'employee_request:approve', 'employee_request:reject', 'employee_request:read', 'legal_entity:read', 'medication_dispense:process', 'medication_dispense:write', 'medication_dispense:reject', 'healthcare_service:read', 'employee_role:read', 'license:read', 'medication_request:details_pharm', 'medication_request:reject_pharm', 'medication_dispense:read_pharm', 'party_verification:details', 'party_verification:write', 'device_dispense:write', 'device_dispense:read', 'device_dispense:stop', 'device_request:read', 'device_dispense:complete', 'device_request:complete', 'device_dispense:mark_in_error', 'medication_request:block_pharm', 'medication_request:unblock_pharm', 'medication_request:read_pharm', 
	],
	'SPECIALIST' => [
		'division:read', 'employee:read', 'employee_request:approve', 'employee_request:reject', 'employee_request:read', 'legal_entity:read', 'otp:read', 'otp:write', 'person:read', 'patient_summary:read', 'encounter:write', 'encounter:read', 'encounter:cancel', 'episode:write', 'episode:read', 'job:read', 'condition:read', 'condition:write', 'observation:read', 'observation:write', 'immunization:read', 'immunization:write', 'allergy_intolerance:read', 'allergy_intolerance:write', 'medication_statement:read', 'medication_statement:write', 'device:read', 'device:write', 'risk_assessment:read', 'risk_assessment:write', 'medication_dispense:read', 'drugs:read', 'medication_request:details', 'medication_request:read', 'medication_request:reject', 'medication_request:resend', 'medication_request_request:read', 'medication_request_request:reject', 'medication_request_request:sign', 'medication_request_request:write', 'diagnostic_report:read', 'diagnostic_report:write', 'diagnostic_report:cancel', 'procedure:read', 'procedure:write', 'procedure:cancel', 'service_request:makeinprogress', 'service_request:complete', 'service_request:recall', 'service_request:cancel', 'service_request:write', 'service_request:read', 'service_request:use', 'approval:create', 'program_service:read', 'medication_administration:read', 'medication_administration:write', 'healthcare_service:read', 'employee_role:read', 'person_request:write', 'person_request:read', 'person_request:sign', 'preperson:read', 'preperson:write', 'authentication_method_request:write', 'merge_request:write', 'merge_request:sign', 'merge_request:read', 'composition:create', 'composition:search', 'composition:read', 'composition:write', 'composition:mark_in_error', 'composition:resend_sms', 'composition_configuration:read', 'composition:sign', 'composition:cancel', 'care_plan:write', 'care_plan:read', 'approval:read', 'approval:cancel', 'license:read', 'clinical_impression:read', 'rule_engine_rule:read', 'medical_event_context:read', 'clinical_impression:write', 'person_verification:details', 'person_emergency_contact:read', 'device_definition:read', 'device_request:write', 'device_request:read', 'device_request:resend', 'device_request:revoke', 'specimen:write', 'specimen:read', 'specimen:process', 'specimen:cancel', 'specimen:reject', 'specimen:invalidate', 'confidant_person_relationship_request:write', 'confidant_person_relationship_request:read', 'confidant_person_relationship:read', 'device_request:mark_in_error', 'device_request:complete', 'device_dispense:read', 'device_association:read', 'detected_issue:read', 'devices_configurations:read', 'device_parameters_configurations:read', 'dictionaries_configurations:read', 'observation_configurations:read', 'care_team:write', 'care_team:read', 'personal_data:read', 'equipment:read', 'equipment:write', 
	],
	'MED_ADMIN' => [
		'diagnostic_report:read', 'diagnostic_report:cancel', 'encounter:read', 'encounter:cancel', 'episode:read', 'procedure:read', 'procedure:cancel', 'person:read', 'preperson:read', 'patient_summary:read', 'division:read', 'employee:read', 'legal_entity:read', 'job:read', 'condition:read', 'observation:read', 'allergy_intolerance:read', 'risk_assessment:read', 'immunization:read', 'license:read', 'reimbursement_report:read', 'medication_request_request:read', 'medication_request:read', 'medication_request:details', 'medication_request:resend', 'medication_request:reject', 'medication_dispense:read', 'medication_request_request:reject', 'clinical_impression:read', 'person_verification:details', 'device_request:read', 'device_request:resend', 'device_request:revoke', 'specimen:read', 'specimen:cancel', 'device_request:mark_in_error', 'device_dispense:read', 'care_team:read', 'composition:read', 'composition:mark_in_error', 'equipment:read', 'device:read', 'device_association:read', 'detected_issue:read', 
	],
	'ASSISTANT' => [
		'division:read', 'employee:read', 'employee_request:approve', 'employee_request:reject', 'employee_request:read', 'legal_entity:read', 'otp:read', 'otp:write', 'person:read', 'patient_summary:read', 'diagnostic_report:read', 'diagnostic_report:write', 'diagnostic_report:cancel', 'procedure:read', 'procedure:write', 'procedure:cancel', 'service_request:write', 'service_request:makeinprogress', 'service_request:complete', 'service_request:read', 'service_request:use', 'service_request:recall', 'service_request:cancel', 'approval:create', 'healthcare_service:read', 'employee_role:read', 'person_request:write', 'person_request:read', 'person_request:sign', 'preperson:read', 'preperson:write', 'job:read', 'observation:read', 'observation:write', 'allergy_intolerance:write', 'medication_statement:write', 'risk_assessment:write', 'medication_administration:write', 'authentication_method_request:write', 'merge_request:write', 'merge_request:read', 'immunization:read', 'care_plan:read', 'approval:read', 'approval:cancel', 'episode:read', 'episode:write', 'encounter:write', 'encounter:read', 'encounter:cancel', 'immunization:write', 'condition:write', 'condition:read', 'license:read', 'medication_request_request:read', 'medication_request:read', 'medication_request:details', 'medication_dispense:read', 'medication_request:resend', 'clinical_impression:read', 'rule_engine_rule:read', 'medical_event_context:read', 'clinical_impression:write', 'person_verification:read', 'person_verification:details', 'person_emergency_contact:read', 'device_definition:read', 'device_request:read', 'device_request:resend', 'specimen:write', 'specimen:read', 'specimen:process', 'specimen:cancel', 'specimen:reject', 'specimen:invalidate', 'confidant_person_relationship_request:read', 'confidant_person_relationship_request:write', 'confidant_person_relationship:read', 'device_dispense:read', 'declaration_request:read', 'declaration_request:write', 'declaration_request:approve', 'declaration_request:reject', 'care_team:write', 'care_team:read', 'care_plan:write', 'device_request:write', 'device_request:revoke', 'device_request:mark_in_error', 'device_request:complete', 'equipment:read', 'equipment:write', 'personal_data:read', 'device:read', 'device_association:read', 'detected_issue:read', 
	],
	'MED_COORDINATOR' => [
		'employee_request:read', 'employee_request:approve', 'employee_request:reject', 'employee_role:read', 'diagnostic_report:read', 'encounter:write', 'encounter:read', 'encounter:cancel', 'episode:write', 'episode:read', 'medical_event_context:read', 'procedure:read', 'person:read', 'preperson:read', 'otp:read', 'otp:write', 'person_request:read', 'authentication_method_request:write', 'merge_request:read', 'patient_summary:read', 'division:read', 'employee:read', 'legal_entity:read', 'job:read', 'condition:read', 'observation:read', 'allergy_intolerance:read', 'risk_assessment:read', 'immunization:read', 'clinical_impression:read', 'service_request:read', 'service_request:write', 'service_request:cancel', 'medication_request:details', 'medication_request:read', 'medication_request:reject', 'medication_request:resend', 'medication_request_request:read', 'medication_request_request:reject', 'medication_request_request:sign', 'medication_request_request:write', 'care_plan:read', 'care_plan:write', 'approval:read', 'approval:cancel', 'approval:create', 'condition:write', 'person_verification:details', 'confidant_person_relationship:read', 'service_request:recall', 'device:read', 'device_association:read', 'detected_issue:read', 
	],
	'ADMIN' => [
		'declaration:read', 'declaration_request:approve', 'declaration_request:reject', 'declaration_request:read', 'declaration_request:sign', 'declaration_request:write', 'capitation_report:read', 'division:details', 'division:read', 'employee:read', 'employee_request:approve', 'employee_request:reject', 'employee_request:read', 'legal_entity:read', 'otp:read', 'otp:write', 'person:read', 'service_request:read', 'service_request:use', 'contract_request:sign', 'contract_request:create', 'contract_request:read', 'contract_request:terminate', 'contract_request:approve', 'contract:read', 'contract:write', 'healthcare_service:read', 'healthcare_service:write', 'employee_role:read', 'employee_role:write', 'device_definition:read', 'equipment:write', 'equipment:read', 'employee_request:write', 'license:read', 'license:details', 'party_verification:details', 'party_verification:write', 'person_verification:details', 
	],
	'OWNER' => [
		'employee_role:write', 'employee_role:read', 'healthcare_service:write', 'healthcare_service:read', 'declaration:read', 'declaration_request:approve', 'declaration_request:read', 'declaration_request:reject', 'declaration_request:write', 'division:activate', 'division:deactivate', 'division:details', 'division:read', 'division:write', 'employee:deactivate', 'employee:details', 'employee:read', 'employee:write', 'employee_request:approve', 'employee_request:read', 'employee_request:reject', 'employee_request:write', 'legal_entity:read', 'otp:read', 'otp:write', 'person:read', 'reimbursement_report:read', 'secret:refresh', 'capitation_report:read', 'contract_request:create', 'contract_request:read', 'contract_request:terminate', 'contract_request:approve', 'contract_request:sign', 'client:read', 'connection:read', 'connection:write', 'connection:refresh_secret', 'connection:delete', 'related_legal_entities:read', 'contract:read', 'contract:write', 'equipment:write', 'equipment:read', 'medical_program_provision:write', 'medical_program_provision:read', 'license:details', 'license:read', 'license:write', 'rule_engine_rule:read', 'party_verification:details', 'party_verification:write', 'person_verification:details', 'device_definition:read', 'device_request:read', 'device_dispense:read', 'medication_dispense:read_pharm', 'party_verification:read', 'care_team:read', 
	],
	'REORGANIZATION_OWNER' => [
		'capitation_report:read', 'client:read', 'connection:read', 'contract:read', 'contract_request:read', 'declaration:read', 'declaration_request:read', 'division:details', 'division:read', 'employee:details', 'employee:read', 'employee_request:read', 'employee_role:read', 'healthcare_service:read', 'legal_entity:read', 'license:details', 'license:read', 'otp:read', 'party_verification:details', 'party_verification:write', 'person:read', 'person_verification:details', 'reimbursement_report:read', 'related_legal_entities:read', 'secret:refresh', 
	],
];
